"""initial schema: subvencion, search, search_result

Revision ID: 550d0a370122
Revises: 
Create Date: 2026-05-17 19:59:03.846749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '550d0a370122'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nif', sa.String(length=16), nullable=False),
    sa.Column('razon_social', sa.Text(), nullable=True),
    sa.Column('cnae', sa.String(length=8), nullable=False),
    sa.Column('tamano', sa.Enum('micro', 'pequena', 'mediana', 'grande', name='tamano_enum'), nullable=False),
    sa.Column('provincia', sa.String(length=2), nullable=False),
    sa.Column('finalidad', postgresql.ARRAY(sa.String(length=64)), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subvencion',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Enum('bdns', 'eu', name='source_enum'), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('titulo', sa.Text(), nullable=False),
    sa.Column('organismo', sa.Text(), nullable=True),
    sa.Column('ambito', sa.Enum('estatal', 'autonomico', 'local', 'ue', name='ambito_enum'), nullable=False),
    sa.Column('ccaa', sa.String(length=64), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('importe_total', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('importe_max_beneficiario', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('porcentaje', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('beneficiarios', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cnae_elegible', postgresql.ARRAY(sa.String(length=8)), nullable=False),
    sa.Column('finalidad', postgresql.ARRAY(sa.String(length=64)), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('enlace_oficial', sa.Text(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('estado', sa.Enum('abierta', 'cerrada', 'proximamente', name='estado_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_subvencion_source_extid')
    )
    op.create_table('search_result',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('search_id', sa.UUID(), nullable=False),
    sa.Column('subvencion_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('razon', sa.Text(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['search_id'], ['search.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subvencion_id'], ['subvencion.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('search_result')
    op.drop_table('subvencion')
    op.drop_table('search')
    # ### end Alembic commands ###
