"""add empresa table

Revision ID: be65eec05f89
Revises: 24243bc3c23c
Create Date: 2026-05-18 09:31:27.132395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'be65eec05f89'
down_revision: Union[str, Sequence[str], None] = '24243bc3c23c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('razon_social', sa.Text(), nullable=False),
    sa.Column('provincia', sa.String(length=2), nullable=True),
    sa.Column('domicilio', sa.Text(), nullable=True),
    sa.Column('objeto_social', sa.Text(), nullable=True),
    sa.Column('hoja_rm', sa.String(length=64), nullable=True),
    sa.Column('capital_social', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('fecha_constitucion', sa.Date(), nullable=True),
    sa.Column('fecha_ultima_act', sa.Date(), nullable=True),
    sa.Column('actos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('estado', sa.Enum('activa', 'disuelta', 'concursal', name='empresa_estado_enum'), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_empresa_hoja_rm'), 'empresa', ['hoja_rm'], unique=True)
    op.create_index(op.f('ix_empresa_provincia'), 'empresa', ['provincia'], unique=False)
    op.create_index(op.f('ix_empresa_slug'), 'empresa', ['slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_empresa_slug'), table_name='empresa')
    op.drop_index(op.f('ix_empresa_provincia'), table_name='empresa')
    op.drop_index(op.f('ix_empresa_hoja_rm'), table_name='empresa')
    op.drop_table('empresa')
    # ### end Alembic commands ###
